# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dae0a9fe28e89f8551532172aa24e7337b9a8584375c63ccc8e699cfebcdd5ff6f5ae7c3d0870b3fcf803f020a69f8460a3012e56ca3047a41bcfb727e54240

test:
  secret_key_base: ff5f3b01d24a917e36c2cf3c9be6a5179fbb94129d444723bc95c797835cd4eca62c0188d10da05819b39e17ff80d1200b90bd8c11c8a13370adb39bceeed254

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
